#!/bin/sh

shell_dir=$( dirname $BASH_SOURCE )

# ls
alias ll='ls -lhG'

# git
source $shell_dir/../git/.git-completion.bash
source $shell_dir/../git/.git-prompt.sh

export PS1='\u@\h:\w$(__git_ps1 " (%s)")\$ '

alias e='emacs -mm'
export EDITOR=emacs