#!/bin/bash

shell_dir=$( dirname $BASH_SOURCE )

# ls
alias ll="ls -lhG"

# git
source $shell_dir/../git/git-completion.bash
source $shell_dir/../git/git-prompt.sh

export PS1='\u@\h:\w$(__git_ps1 " (%s)")\$ '

# emacs

EMACS="emacs"
# The default Mac OS X emacs does not support -mm
# We need to exclude it
if [[ "Darwin" != "$(uname)" ]]; then
  EMACS="${EMACS} -mm"
fi
export EDITOR="${EMACS}"

alias e="${EMACS}"

# Open a file with emacs in the read-only mode
er()
{
  e $@ --eval '(setq buffer-read-only t)'
}

alias g=gradle
